Add registration info for #20
pirxthepilot/wtfis pull request #21
Opened 2022-10-25 13:41 UTC by plehr

2022-10-26 01:31 UTC, pirxthepilot requested changes

2022-10-26 01:31 UTC, pirxthepilot commented on README.md
> +* [Whois](https://api.riskiq.net/api/whois_pt/) [(registration)](https://community.riskiq.com/registration/wtfis)
Seems to work as well with just a trailing slash: https://community.riskiq.com/registration/ . Mind updating to this? Thanks for the PR!

2023-01-26 12:48 UTC, Jack12816 commented
Nice! This is very helpful. :+1:

2023-02-20 07:16 UTC, pirxthepilot commented
The info here has been incorporated into #42.

2023-02-20 07:16 UTC, closed without merging